packages:
  - apps/*
  - packages/*

versions:
  angular: &angular 21.0.3
  angular-build: &angular-build 21.0.2
  angular-cdk: &angular-cdk 21.0.2
  angular-eslint: &angular-eslint 21.1.0
  class-variance-authority: &cva 0.7.1
  clsx: &clsx 2.1.1
  compression: &compression 1.8.1
  cookie: &cookie 1.1.1
  dotenv: &dotenv 17.2.3
  esbuild: &esbuild 0.27.1
  hast-util-to-html: &hast-util-to-html 9.0.5
  highlight-js: &highlight-js 11.11.1
  katex: &katex 0.16.27
  lowlight: &lowlight 3.3.0
  ngx-translate-core: &ngx-translate-core 17.0.0
  eslint: &eslint 9.39.1
  eslint-eslintrc: &eslint-eslintrc 3.3.3
  eslint-plugin-boundaries: &eslint-plugin-boundaries 5.3.1
  eslint-plugin-jest: &eslint-plugin-jest 29.2.1
  eslint-plugin-storybook: &eslint-plugin-storybook 10.1.2
  eslint-plugin-testing-library: &eslint-plugin-testing-library 7.13.5
  eslint-plugin-turbo: &eslint-plugin-turbo 2.6.3
  google-auth-library: &google-auth-library 10.5.0
  husky: &husky 9.1.7
  jest: &jest 30.2.0
  jsdom: &jsdom 27.3.0
  lint-staged: &lint-staged 16.2.7
  node: &node 24.10.1
  nestjs: &nestjs 11.1.9
  nestjs-cli: &nestjs-cli 11.0.14
  ngxs: &ngxs 20.1.0
  playwright: &playwright 1.57.0
  postcss: &postcss 8.5.6
  prettier: &prettier 3.7.4
  prisma: &prisma 7.1.0
  rimraf: &rimraf 6.1.2
  rx-angular: &rx-angular 20.1.0
  rx-angular-isr: &rx-angular-isr 20.0.0
  rxjs: &rxjs 7.8.2
  storybook: &storybook 10.1.4
  supabase: &supabase 2.86.2
  swc: &swc 1.15.3
  tailwind-merge: &tailwind-merge 3.4.0
  tailwindcss: &tailwindcss 4.1.17
  tiptap: &tiptap 3.13.0
  tslib: &tslib 2.8.1
  turbo: &turbo 2.6.3
  types-katex: &types-katex 0.16.7
  typescript: &typescript 5.9.3
  typescript-eslint: &typescript-eslint 8.48.1
  unplugin-swc: &unplugin-swc 1.5.9
  vite: &vite 7.2.7
  vitest: &vitest 4.0.15

catalog:
  '@angular/animations': *angular
  '@angular/build': *angular-build
  '@angular/cdk': *angular-cdk
  '@angular/cli': *angular-build
  '@angular/common': *angular
  '@angular/compiler': *angular
  '@angular/compiler-cli': *angular
  '@angular/core': *angular
  '@angular-eslint/eslint-plugin': *angular-eslint
  '@angular-eslint/eslint-plugin-template': *angular-eslint
  '@angular-eslint/schematics': *angular-eslint
  '@angular-eslint/template-parser': *angular-eslint
  '@angular/forms': *angular
  '@angular/platform-browser': *angular
  '@angular/platform-server': *angular
  '@angular/router': *angular
  '@angular/ssr': *angular-build
  '@eslint/eslintrc': *eslint-eslintrc
  '@eslint/js': *eslint
  '@nestjs/cli': *nestjs-cli
  '@nestjs/common': *nestjs
  '@nestjs/core': *nestjs
  '@nestjs/platform-express': *nestjs
  '@nestjs/testing': *nestjs
  '@ngx-translate/core': *ngx-translate-core
  '@ngxs/devtools-plugin': *ngxs
  '@ngxs/form-plugin': *ngxs
  '@ngxs/store': *ngxs
  '@prisma/adapter-pg': *prisma
  '@prisma/client': *prisma
  '@prisma/client-runtime-utils': *prisma
  '@rx-angular/cdk': *rx-angular
  '@rx-angular/isr': *rx-angular-isr
  '@rx-angular/template': *rx-angular
  '@storybook/addon-a11y': *storybook
  '@storybook/addon-vitest': *storybook
  '@storybook/angular': *storybook
  '@supabase/supabase-js': *supabase
  '@swc/core': *swc
  '@tailwindcss/postcss': *tailwindcss
  '@tiptap/core': *tiptap
  '@tiptap/extension-image': *tiptap
  '@tiptap/extension-code-block-lowlight': *tiptap
  '@tiptap/extension-placeholder': *tiptap
  '@tiptap/pm': *tiptap
  '@tiptap/starter-kit': *tiptap
  '@types/katex': *types-katex
  '@types/node': *node
  '@typescript-eslint/eslint-plugin': *typescript-eslint
  '@typescript-eslint/parser': *typescript-eslint
  '@vitest/coverage-v8': *vitest
  class-variance-authority: *cva
  clsx: *clsx
  compression: *compression
  cookie: *cookie
  dotenv: *dotenv
  esbuild: *esbuild
  eslint: *eslint
  hast-util-to-html: *hast-util-to-html
  highlight.js: *highlight-js
  katex: *katex
  lowlight: *lowlight
  eslint-plugin-boundaries: *eslint-plugin-boundaries
  eslint-plugin-jest: *eslint-plugin-jest
  eslint-plugin-storybook: *eslint-plugin-storybook
  eslint-plugin-testing-library: *eslint-plugin-testing-library
  eslint-plugin-turbo: *eslint-plugin-turbo
  google-auth-library: *google-auth-library
  husky: *husky
  jest: *jest
  jest-environment-jsdom: *jest
  jsdom: *jsdom
  lint-staged: *lint-staged
  playwright: *playwright
  postcss: *postcss
  prettier: *prettier
  prisma: *prisma
  rimraf: *rimraf
  rxjs: *rxjs
  storybook: *storybook
  tailwind-merge: *tailwind-merge
  tailwindcss: *tailwindcss
  turbo: *turbo
  tslib: *tslib
  typescript: *typescript
  typescript-eslint: *typescript-eslint
  unplugin-swc: *unplugin-swc
  vite: *vite
  vitest: *vitest

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - lmdb
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
