packages:
  - apps/*
  - packages/*

catalog:
  '@nestjs/core': 11.1.8
  '@tiptap/core': 3.10.1
  '@tiptap/pm': 3.10.1
  '@types/node': 24.9.2
  eslint: 9.39.0
  google-auth-library: 10.5.0
  husky: 9.1.7
  jest: 30.2.0
  next: 16.0.1
  prettier: 3.6.2
  prisma: 6.18.0
  react: 19.2.0
  storybook: 10.0.2
  stylelint: 16.25.0
  tailwindcss: 4.1.16
  turbo: 2.6.0
  typescript: 5.9.3
  vitest: 4.0.6

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
