packages:
  - apps/*
  - packages/*

versions:
  '@tanstack/react-form': &tanstack-react-form 1.23.7
  '@tanstack/react-query': &tanstack-react-query 5.90.7
  eslint: &eslint 9.39.1
  google-auth-library: &google-auth-library 10.5.0
  husky: &husky 9.1.7
  jest: &jest 30.2.0
  ky: &ky 1.14.0
  lint-staged: &lint-staged 16.2.6
  next: &next 16.0.1
  node: &node 24.9.2
  nestjs: &nestjs 11.1.8
  playwright: &playwright 1.56.1
  prettier: &prettier 3.6.2
  prisma: &prisma 6.19.0
  react: &react 19.2.0
  rxjs: &rxjs 7.8.2
  storybook: &storybook 10.0.6
  stylelint: &stylelint 16.25.0
  supabase: &supabase 2.80.0
  tailwindcss: &tailwindcss 4.1.17
  tiptap: &tiptap 3.10.4
  turbo: &turbo 2.6.0
  typescript: &typescript 5.9.3
  vitest: &vitest 4.0.8
  zod: &zod 4.1.12
  zustand: &zustand 5.0.8

catalog:
  '@nestjs/common': *nestjs
  '@nestjs/core': *nestjs
  '@nestjs/platform-express': *nestjs
  '@nestjs/testing': *nestjs
  '@prisma/client': *prisma
  '@storybook/addon-a11y': *storybook
  '@storybook/addon-vitest': *storybook
  '@storybook/nextjs-vite': *storybook
  '@supabase/supabase-js': *supabase
  '@tailwindcss/postcss': *tailwindcss
  '@tanstack/react-form': *tanstack-react-form
  '@tanstack/react-query': *tanstack-react-query
  '@tiptap/core': *tiptap
  '@tiptap/extension-image': *tiptap
  '@tiptap/extension-code-block-lowlight': *tiptap
  '@tiptap/extension-placeholder': *tiptap
  '@tiptap/pm': *tiptap
  '@tiptap/react': *tiptap
  '@tiptap/starter-kit': *tiptap
  '@types/node': *node
  '@vitest/browser': *vitest
  '@vitest/browser-playwright': *vitest
  '@vitest/coverage-v8': *vitest
  eslint: *eslint
  google-auth-library: *google-auth-library
  husky: *husky
  jest: *jest
  jest-environment-jsdom: *jest
  ky: *ky
  lint-staged: *lint-staged
  next: *next
  playwright: *playwright
  prettier: *prettier
  prisma: *prisma
  react: *react
  react-dom: *react
  rxjs: *rxjs
  storybook: *storybook
  stylelint: *stylelint
  tailwindcss: *tailwindcss
  turbo: *turbo
  typescript: *typescript
  vitest: *vitest
  zod: *zod
  zustand: *zustand

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
