packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': 22.18.10
  '@tiptap/pm': 3.10.1

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
