export const ERROR_CODE = {
  // System
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  EMAIL_ACCESS_DENIED: 'EMAIL_ACCESS_DENIED',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Media
  MEDIA_FILE_EXTENSION_MISSING: 'MEDIA_FILE_EXTENSION_MISSING',

  // Storage
  SIGNED_DOWNLOAD_URL_CREATION_FAILED: 'SIGNED_DOWNLOAD_URL_CREATION_FAILED',
  SIGNED_UPLOAD_URL_CREATION_FAILED: 'SIGNED_UPLOAD_URL_CREATION_FAILED',

  // Article
  ARTICLE_NOT_FOUND: 'ARTICLE_NOT_FOUND',
  ARTICLE_ACCESS_DENIED: 'ARTICLE_ACCESS_DENIED',

  // Page
  PAGE_NOT_FOUND: 'PAGE_NOT_FOUND',
} as const;

// --- 型定義 ---
export type ErrorCode = keyof typeof ERROR_CODE;

export type InternalServerErrorCode =
  | typeof ERROR_CODE.INTERNAL_SERVER_ERROR
  | typeof ERROR_CODE.SIGNED_DOWNLOAD_URL_CREATION_FAILED
  | typeof ERROR_CODE.SIGNED_UPLOAD_URL_CREATION_FAILED;

export type NotFoundCode =
  | typeof ERROR_CODE.USER_NOT_FOUND
  | typeof ERROR_CODE.ARTICLE_NOT_FOUND
  | typeof ERROR_CODE.PAGE_NOT_FOUND;

export type ForbiddenCode = typeof ERROR_CODE.ARTICLE_ACCESS_DENIED | typeof ERROR_CODE.EMAIL_ACCESS_DENIED;

export type BadRequestCode = typeof ERROR_CODE.MEDIA_FILE_EXTENSION_MISSING;

export type UnauthorizedCode = typeof ERROR_CODE.UNAUTHORIZED;
