name: Deploy

on:
  push:
    branches: [develop, main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name }}

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          token_format: 'access_token'
          create_credentials_file: true
          export_environment_variables: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit . --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }} --suppress-logs

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ secrets.SERVICE_NAME }}
          region: ${{ vars.REGION }}
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}
          flags: '--allow-unauthenticated'
          secrets: |
            DATABASE_URL=database-url:latest
            DIRECT_URL=direct-url:latest
            SUPABASE_URL=supabase-url:latest
            SUPABASE_SERVICE_ROLE_KEY=supabase-service-role-key:latest
            CORS_ORIGINS=cors-origins:latest
            APP_URL=app-url:latest
            API_URL=api-url:latest
            COOKIE_DOMAIN=cookie-domain:latest
